services:
  - type: web
    name: blog-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.12.6"
    # envVars:
    #   - key: DATABASE_URL
    #     value: postgres://username:password@hostname:port/dbname
    autoDeploy: true
    # regions:
    #   - oregon
    #   - virginia
    #   - singapore
    #   - frankfurt
    #   - sydney
    #   - japan